steps:
  # Gradle을 사용하여 애플리케이션을 빌드합니다.
  # 이 단계에서 build/libs/*.jar 파일이 생성됩니다.
  - name: 'gradle'
    args: ['build']

  # Docker 이미지를 빌드합니다.
  # 이전 단계에서 생성된 .jar 파일을 Docker 이미지에 복사합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sejali-server', '.']

  # 빌드된 Docker 이미지를 Container Registry에 푸시합니다.
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sejali-server']
images:
  - 'gcr.io/$PROJECT_ID/sejali-server'