steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/sejali',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'sejali-server',  # Cloud Run 서비스 이름
      '--image=gcr.io/$PROJECT_ID/sejali',
      '--region=us-central1',
      '--platform=managed',
      '--allow-unauthenticated'
    ]

images:
  - 'gcr.io/$PROJECT_ID/sejali'

options:
  logging: CLOUD_LOGGING_ONLY
